# Copyright (C) 2022 - TODAY, Jescalante@blueminds.cl
# License AGPL-3.0 or later (http://www.gnu.org/licenses/agpl).

{
    'name': 'Agreement Blueminds',
    'summary': "Adds an agreement object",
    'version': '1.0',
    'category': 'Contract',
    'author': 'Akretion,'
              'Jamie Escalante (jescalante@blueminds.cl), '
              ' (Bluemindsspa)',
    'website': 'https://www.blueminds.cl/',
    'license': 'AGPL-3',
'depends': ['contacts', 'product', 'stock', 'crm', 'mail', 'sale_management', 'fleet', 'rowno_in_tree', 'stock', 'l10n_cl_edi'],
    'data': [
        'data/ir_sequence.xml',
        'data/module_category.xml',
        'data/agreement_stage.xml',
        'data/agreement_type.xml',
        'data/agreement_data.xml',
        'data/payment_method_partner_data.xml',
        'data/comunas.xml',
        'security/ir.model.access.csv',
        'security/agreement_security.xml',
        "report/agreement.xml",
        #'report/extra_ids.xml',
        'views/agreement.xml',
        'views/agreement_type.xml',
        'views/res_config_settings.xml',
        'views/agreement_appendix.xml',
        'views/agreement_clause.xml',
        'views/agreement_recital.xml',
        'views/agreement_section.xml',
        'views/agreement_stages.xml',
        'views/agreement_type.xml',
        'views/agreement_subtype.xml',
        'views/agreement_renewaltype.xml',
        'views/agreement_increasetype.xml',
        'wizard/create_test.xml',
        'views/agreement_line.xml',
        'views/agreement_discount.xml',
        'views/agreement_extra.xml',
        'views/zona_view.xml',
        'views/product_template.xml',
        'views/sale_order.xml',
        'views/crm_lead_view.xml',
        'views/crm_team_view.xml',
        #'views/product_pricelist_views.xml',
        'views/modelos_view.xml',
        'views/res_partner.xml',
        'views/fleet_vehicle_view.xml',
        'data/cron_agreement_discount_data.xml',
        'views/menu.xml',
        ],
    #'demo': ['demo/demo.xml'],
    'qweb': [
            "static/src/xml/domain_widget_view.xml"
        ],
    'development_status': 'Beta',
    'maintainers': [
        'Jamie Escalante, jescalante@blueminds.cl',
    ],
    'installable': True,
}
