# License AGPL-3.0 or later (http://www.gnu.org/licenses/agpl).
# Jamie Escalante, (jescalante@blueminds.cl)

from . import (
    res_config_settings,
    agreement_stage,
    agreement,
    agreement_appendix,
    agreement_clause,
    agreement_line,
    agreement_recital,
    agreement_section,
    agreement_type,
    agreement_subtype,
    product_template,
    agreement_renewaltype,
    agreement_increasetype,
    documents,
    rentals_line,
    agreement_move,
    agreement_extra,
    zona,
    means,
    capabilities,
    account_move,
    crm_lead,
    #product_pricelist,
    sii_reference,
    res_partner,
    sale_order,
    crm_team,
    fleet_vehicle,
    modelos,
    sale_order_detail,
)
